// export const DOMAIN = 'https://movieapi.cyberlearn.vn'
export const DOMAIN = 'http://localhost:8080'
export const DOMAIN2 = 'http://localhost:8080'
export const TOKEN = 'accessToken'
export const GROUPID = 'GP00'
export const USER_LOGIN = 'USER_LOGIN'